spring:
  application:
    name: sca-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        ip: 127.0.0.1
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
      datasource.ds1.nacos:
        server-addr: localhost:8848
        data-id: sentinel-degrade-rule
        rule-type: degrade
      datasource.ds2.nacos:
        server-addr: localhost:8848
        data-id: sentinel-consumer-flow-rule
        rule-type: flow

resttemplate:
  sentinel:
    enabled: true

feign:
  sentinel:
    enabled: true

spring.cloud.stream:
  rocketmq:
#    bindings.input.consumer:
#      orderly: true
    binder.name-server: localhost:9876
  bindings.input:
    destination: binder-topic
    content-type: application/json
    group: yunqi-group

server:
  port: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000


logging.level.com.alibaba.nacos: ERROR
